name: text_rpg_client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  get: ^4.6.5
  get_storage: ^2.0.3
  validators: ^3.0.0
  url_launcher: ^6.1.10
  intl: ^0.17.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Yd2002
      fonts:
        - asset: assets/fonts/yd2002.ttf
    - family: SonySketchEF
      fonts:
        - asset: assets/fonts/Sony_Sketch_EF.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21